### ISSUE TITLE
Error while starting controller-Cannot find required executable ovs-controller.

### ISSUE THREAD

**Issue by ronjohn320** [PrincetonUniversity/Coursera-SDN#48] opened 2015-08-09 12:54 UTC
vagrant@coursera-sdn:~$ sudo mn
**\* Creating network
**\* Adding controller
**\* Adding hosts:
h1 h2
**\* Adding switches:
s1
**\* Adding links:
(h1, s1) (h2, s1)
**\* Configuring hosts
h1 h2
**\* Starting controller
Cannot find required executable ovs-controller.
Please make sure that it is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
vagrant@coursera-sdn:~$

**Comment by feamster** [comment] 2015-08-09 15:54
This is not a bug with the distribution, but with your setup.  Use Piazza for unconfirmed bugs.  Closing this issue.

**Closed as completed by feamster** 2015-08-09 15:54 UTC
