### ISSUE TITLE
Couldn't clone the course repository

### ISSUE THREAD

**Issue by sufunchen** [PrincetonUniversity/Coursera-SDN#19] opened 2015-06-14 11:35 UTC
I tried to access the github to clone the SDN course repository but received the following error messages:

Cloning into 'courserta-SDN'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

What should I do to correct this so I could clone the course repository?
Thanks!

**Comment by feamster** [comment] 2015-06-14 11:58
You have a typo in your clone command.  This is not a bug.  Please don't post unconfirmed issues to the issue tracker.  I'm closing this.

**Closed as completed by feamster** 2015-06-14 11:58 UTC
Labels: invalid
