### ISSUE TITLE
Programming Assignment 5.1

### ISSUE THREAD

**Issue by peteraw** [PrincetonUniversity/Coursera-SDN#27] opened 2015-06-26 05:37 UTC
I've not edited anyting. Just using existing files run (a) mininet with Enter prompt (b) launch NetASM data path (c) once I started POX, NetASM datapath start throwing errors. Is this supposed to do that. 

vagrant@coursera-sdn:~$ sudopy python /home/vagrant/pox/pox.py --no-openflownetasm.back_ends.soft_switch.datapath --address=127.0.0.1 --port=6633 -dpid=0000000000000001 --policy= --ports=s1-eth1,s
1-eth2 --ctl_port=7791
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:core:POX 0.2.0 (carp) is up.
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:dp.00-00-00-00-00-01:Connected to controller
Policy [netasm.examples.learning_switch_acl.learning_switch_acl_netasm](type check): passed!
policy [netasm.examples.learning_switch_acl.learning_switch_acl_netasm](original cost): Area=4704,
Latency=44
Policy [netasm.examples.learning_switch_acl.learning_switch_acl_netasm](optimize cost): Area=4080,
Latency=39
ERROR:ControllerConnection(id=1):Exception handling KeyError
Traceback (most recent call last):
  File "/home/vagrant/pox/pox/datapaths/switch.py", line 1167, in read
    self.on_message_received(self, msg_obj)
  File "/home/vagrant/pox/pox/datapaths/switch.py", line 245, in rx_message
    h(msg, connection=connection)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 472, in _rx_vendor
    self._handle_out_message(message, connection)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 497, in _handle_out_mes
sage
    self.policy.add_table_entry(t_id, t_index, t_entry)
  File "/home/vagrant/netasm/netasm/netasm/core/execute/multi_process.py", line 810, in add_table_en
try
    self._tables[id].input_interface.put(('add_entry', (index, entry)))
KeyError: TableId('acl_match_table')
ERROR:ControllerConnection(id=1):Exception handling KeyError
Traceback (most recent call last):
  File "/home/vagrant/pox/pox/datapaths/switch.py", line 1167, in read
    self.on_message_received(self, msg_obj)
  File "/home/vagrant/pox/pox/datapaths/switch.py", line 245, in rx_message
    h(msg, connection=connection)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 472, in _rx_vendor
    self._handle_out_message(message, connection)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 497, in _handle_out_mes
sage
    self.policy.add_table_entry(t_id, t_index, t_entry)
  File "/home/vagrant/netasm/netasm/netasm/core/execute/multi_process.py", line 810, in add_table_en
try
    self._tables[id].input_interface.put(('add_entry', (index, entry)))
KeyError: TableId('acl_match_table')
♥INFO:core:Going down...
INFO:core:Down.

**Comment by feamster** [comment] 2015-06-27 08:52
This is not a bug with the setup, but rather with your code.  Please only post confirmed errors here.  Use Piazza to debug your assignments.  Closing this.

**Closed as completed by feamster** 2015-06-27 08:52 UTC
Labels: invalid
